# Numpy

In [1]:
import numpy as np


In [2]:
a = np.array([2,3,4,6,2])
a

array([2, 3, 4, 6, 2])

In [3]:
b = np.array([[[1,2,3,4],
              [1,2,3,4]]])
b.shape

(1, 2, 4)

In [4]:
a.shape

(5,)

In [5]:
b.ndim


3

In [6]:
c = np.array([2,3,42.,6,2])
c

array([ 2.,  3., 42.,  6.,  2.])

In [7]:
c.dtype


dtype('float64')

In [8]:
a.size



5

In [9]:
type(a)


numpy.ndarray

In [10]:
b = np.array([6, 7, 8.0,'a'])

b

array(['6', '7', '8.0', 'a'], dtype='<U32')

In [11]:
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

In [12]:
# array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [13]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ], dtype=int )
c

array([[1, 2],
       [3, 4]])

In [14]:
#The function zeros creates an array full of zeros
np.ones( (3,4) ,dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
#universal functions such as sqrt, sin, cos etc.,
d = np.arange(30).reshape(3,5,2)
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [16]:
#Indexing Arrays
a = np.arange(90000).reshape(900,100)**40
a


array([[                   0,                    1,        1099511627776,
        ..., -1386813847010951423,  1869980107288870912,
         -599374982674989791],
       [                   0,  -883952211225130911,    19880269741817856,
        ...,  5738201100363168609,  7403109646350680064,
         4363012035490685889],
       [                   0,  2123839716503765569, -9130941591865786368,
        ..., -7078394609266374335, -4119138894044200960,
        -6831036904872630303],
       ...,
       [                   0, -3610438897839622047,  2922450229582102528,
        ...,  4133360441460517729,  7963807799958306816,
         3570624251556590529],
       [                   0,  7483093382935867969,  6251102935418142720,
        ...,  5313251541496789313,  2579965551669411840,
         4989625787575810017],
       [                   0, -7755738349101590111,  5195818063357804544,
        ...,  4580067539581703329,    75366024525905920,
         -404816005462303359]])

In [17]:
#Shape Manipulation

a = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print(a,'\n')
print(b)


[[0 1]
 [2 3]] 

[[11 12]
 [13 14]]


In [20]:
c=np.vstack((a,b))
print(c)
c.shape

[[ 0  1]
 [ 2  3]
 [11 12]
 [13 14]]


(4, 2)

In [21]:
np.hstack((a,b))


array([[ 0,  1, 11, 12],
       [ 2,  3, 13, 14]])

In [22]:
e =int(np.random.random()*1000)
e

540

In [23]:
int(np.ceil(11.9))

12

In [24]:
#Splitting Arrays
a = np.floor(100*np.random.random((3,6)))
print(a)


[[ 9. 16. 15. 96. 77. 58.]
 [99. 10. 48. 87. 58. 31.]
 [62. 81.  4. 39. 38.  2.]]


In [25]:
f = np.hsplit(a,2)   # Split a into 2
print(f[0])
print("\n")
print(f[1])

[[ 9. 16. 15.]
 [99. 10. 48.]
 [62. 81.  4.]]


[[96. 77. 58.]
 [87. 58. 31.]
 [39. 38.  2.]]


In [26]:
#Copies and Views

# No Copy at All¶

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b = a            # no new object is created
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a[5] = 160
a

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [29]:
b

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [30]:
b.shape = 3,4    # changes the shape of a.shape(3, 4)

In [31]:
a.shape

(3, 4)

In [32]:
c.base is a  
a.shape
a

array([[  0,   1,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [33]:
c.shape = 2,4                      # a's shape doesn't change
print(a.shape)
c

(3, 4)


array([[ 0,  1,  2,  3],
       [11, 12, 13, 14]])

In [34]:
c[0,1] = 999                    # a's data changes
c

array([[  0, 999,   2,   3],
       [ 11,  12,  13,  14]])

In [35]:
a

array([[  0,   1,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [36]:
# Deep Copy

b = a.copy() 


In [37]:
b

array([[  0,   1,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])